name: "Build Api"
"on":
  push:
    branches: [dev]
    paths:
      - api/**
      - .github/workflows/ci.api.yml

env:
  WORKING_DIR: "api"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            ${{ env.WORKING_DIR }}/go.mod
            ${{ env.WORKING_DIR }}/go.sum

      - name: Install dependencies
        run: go mod tidy
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          working-directory: ${{ env.WORKING_DIR }}
          version: latest
          args: --timeout 5m

      - name: Run tests
        run: go test ./...
        working-directory: ${{ env.WORKING_DIR }}

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag ochom/streamx:latest
        working-directory: ${{ env.WORKING_DIR }}

      - name: Tag to GHCR
        run: |
          docker tag ochom/streamx:latest ghcr.io/ochom/streamx:latest

      - name: Push image
        run: |
          docker push ochom/streamx:latest
          docker push ghcr.io/ochom/streamx:latest
