name: "Build Api"
"on":
  push:
    branches: [dev]
    paths:
      - api/**
      - .github/workflows/ci.api.yml

env:
  WORKING_DIR: "api"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag ochom/streamx:latest
        working-directory: ${{ env.WORKING_DIR }}

      - name: Push image
        run: |
          docker push ochom/streamx:latest
