name: "Build Core"
"on":
  push:
    branches: [dev]
    paths:
      - core/**
      - .github/workflows/ci.core.yml

env:
  WORKING_DIR: "core"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: |
            ${{ env.WORKING_DIR }}/go.mod
            ${{ env.WORKING_DIR }}/go.sum

      - name: Install dependencies
        run: go mod tidy
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          working-directory: ${{ env.WORKING_DIR }}
          version: latest
          args: --timeout 5m

      - name: Run tests
        run: go test ./...
        working-directory: ${{ env.WORKING_DIR }}
